// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function CreateEntry(arg1:string,arg2:string):Promise<void>;

export function DeleteEntryApp(arg1:number):Promise<void>;

export function GetEntries():Promise<Array<entities.Entry>>;

export function GetEntry(arg1:number):Promise<entities.Entry>;

export function UpdateEntry(arg1:entities.Entry):Promise<void>;
