// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function CreateEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetEntries():Promise<Array<entities.Entry>>;
