// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry(arg1, arg2) {
  return window['go']['main']['App']['CreateEntry'](arg1, arg2);
}

export function DeleteEntryApp(arg1) {
  return window['go']['main']['App']['DeleteEntryApp'](arg1);
}

export function GetEntries() {
  return window['go']['main']['App']['GetEntries']();
}

export function GetEntry(arg1) {
  return window['go']['main']['App']['GetEntry'](arg1);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}
